### ISSUE TITLE
P2P OT

### ISSUE THREAD

**Issue by vijayee** [ottypes/text#4]
Has any attempt been made at this yet that you are aware of? I'd like to take a stab at it if it doesn't exist.

**Comment by josephg** [comment]
Nope not really - at least not by me. I've thought about it a bunch though.

There's a bunch of issues to be aware of, like if you have three people editing a document in a p2p context (A, B and C). A inserts at the start, B inserts at the end and C deletes the whole document. Obviously A's insert should be before B's insert, but if A and B find out about C's delete first its possible for their inserts to get out of order. With a centralised server everything always reduces to basically 2 nodes (server and client) and we can just make it sometimes be *consistently* out of order.

With 3 nodes in a p2p setting there are ways they can trade their operations around that won't be consistent. The solution for text (and lists) is to add tombstones. So, you don't actually delete characters - just mark them deleted then run-length encode them. I have an implementation of this OT type which does this here: https://github.com/ottypes/text-tp2 . If you're building a p2p system you might want to use that instead.

Anyway, good luck! Let me know how it goes!

**Comment by vijayee** [comment]
I was thinking maybe some sort of consensus algorithm would be attached to the document like a Gossip clock to ensure ordering by time.  I'll check this repo out. Thanks for your insight!
