### ISSUE TITLE
Why is the text ot-type not invertable?

### ISSUE THREAD

**Issue by aldendaniels** [ottypes/text#7]
@josephg - Thank you for your remarkable work over the years that has helped make collaborative editing accessible to the JavaScript community. I wrote my own OT implementation for http://codr.io/, a collaborative text editor, but it lacks the robustness that the text OT provides. I'd like to switch to using this library.

The only hangup I'm having with the text OT type is that it's not invertible. For undo, I of course need to invert operations. I do this myself (turn insert into delete, for example), but I'm guessing this simple approach is naive, since you decided against providing an invert function. 

Would you mind elaborating as to why this type is non-invertible?

Thanks!

**Comment by josephg** [comment]
Sure, although its not super interesting. The reasons are:

- Add complexity (although really very little complexity in the case of text)
- Its basically impossible to add invertibility for TP2 implementations
- Invertible OT types aren't needed for undo.

Invertibility makes time travelling easier to implement on the server (without it you need keyframes or something like it), but thats about it. To implement undo in the client you can calculate an operation's inverse at the same time as the edit happens, and add that to the undo stack. If a document is 'ABCDE' and the user deletes 'DE', you calculate & send to the server [skip 3, delete 2], and add [skip 3, insert 'DE'] in the local undo stack. That undo stack entry can be transformed by incoming edits just like if the type were invertible from the start.

You can construct any operation's inverse from an operation and a copy of the document it is to be applied against, although I haven't written a helper function to do this. (Should be pretty easy to both write and to add a unit test for. Inserts turn into deletes and for deletes you find the corresponding text and insert it. Happy to accept a PR if you like, though it'll need tests.)

Glad you found the code useful!

**Comment by aldendaniels** [comment]
Hey Joseph, I meant to respond to your answer and dropped the ball. Thanks for the explanation - I hadn't understood how invertability was different than just creating the inverse action as you suggest. Your answer + some research has helped to resolve my confusion. Cheers.
