### ISSUE TITLE
Will there be support for "sr" or "string replace"?

### ISSUE THREAD

**Issue by adelriosantiago** [ottypes/text#8]
I've found that some sort of "string replace" is needed in some cases. For example:

- A and B have: "start|" (caret is represented as |)
- A writes an x: "startx|"
- B replaces the x: "startX|"
- A will end up with: "start|X"

Because behind the scenes the operations are ""string delete" and then "string insert" and not a real "string replace".

Any thoughts how to implement this?

**Comment by josephg** [comment]
I don't understand the use case.

- A and B have "start|"
- A writes an 'x' at position 5 (-> "startx|")
- B replaces the x with X (skip 5, remove 1, insert X)
- A will end up with "startX|"

How does A get "start|X"?

**Comment by adelriosantiago** [comment]
@josephg You are right. I think this is a [ShareDB](https://github.com/share/sharedb) issue. It uses your library and seems to break down operations into multiple steps. 

The operation _skip 5, remove 1, insert X_ would then be something like _skip 5, remove 1_ and _skip 5, insert X_, meaning that in some point in time the text is only "start|" the caret is of course moved because it can't be something like "start |".

**Comment by josephg** [comment]
Ah I didn’t realise the | was a caret. And yeah, that sounds like a bug in the transformCursor code. I don’t think you need a replace operation to fix that issue.
